# Generated by Django 4.2.6 on 2023-10-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(help_text='Brief description of the product.', max_length=255, null=True),
        ),
    ]
